#!/bin/bash

# ici creaiton des configuration pour l'execution de l'application : creation de user 


# Crée un utilisateur système "myapp" s'il n'existe pas déjà
if ! id "myapp" >/dev/null 2>&1; then
    echo "... creating user myapp for the service ..."
    sudo useradd -r myapp
else 
    echo "... user myapp already exist , skip creation ..."
fi


# Changer le propretaire du fichier des donnée de l'application
echo "Giving owership of data file to the service user"
sudo chown myapp:myapp /var/lib/myapp/myapp.data

echo "l'application a été installée avec succès"

########
########


echo "Demarrage du service de l'application . . ."

# Recharger systemd pour prendre en compte le nouveau fichier .service
systemctl daemon-reload

# Démarrer immédiatement le service
systemctl start myapp.service

echo "Service demarré avec succès . . ."