services:
  mysql:
    image: quay.io/keycloak/keycloak:${KEYCLOACK_VERSION}
    container_name: auth
    env_file:
      - .env
    # ports:
    #   - "8443:${KEYCLOAK_PORT}"
    network_mode: host
    command:
      - start
    volumes:    
    #   - ${KEYCLOAK_DATA_VOLUME_DIR}:/var/lib/mysql
      - /etc/ssl/certs/my-autosigne-cert/:/etc/x509/https:ro
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}                       
        # reservations:
        #   memory: ${MEM_RESERVATION}                
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${KEYCLOAK_PORT} || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}