# version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    env_file:
      - .env
    # ports:
    #   - "80:${HTTP_PORT}"
    #   - "443:${HTTPS_PORT}"
    network_mode: host
    volumes:    
      - ${NGINX_SSL_CERT_DIR}:${SSL_CERT_DIR}
      - ${NGINX_WELCOME_PAGE_DIR}:${WELCOME_PAGE_DIR}
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}                       
        reservations:
          memory: ${MEM_RESERVATION}                
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
