---
# defition des host sur lequel s'execute le playbook
- name: Install zabbix agent
  hosts: local
  become: yes
  vars:
    configFile: /home/albarry/Bureau/DevOps/MyLabDir/ansible/file.txt
    FQDN: localhost
    ServerName: zabbix_server

  tasks:

  # config zabbix agent ip
  - name: config server ip
    ansible.builtin.lineinfile:
      path: '{{configFile}}'
      regexp: '^ServerActive='
      line: 'ServerActive={{FQDN}}'

  # config zabbix agent hostame
  - name: config server name
    ansible.builtin.lineinfile:
      path: '{{configFile}}'
      regexp: '^Hostname'
      line: 'Hostname={{ServerName}}'

  # register file contente for showing it
  - name: Display the content of config file
    command: cat '{{configFile}}'
    register: file_content

  # show the file contente
  - name: Show file content
    debug:
      msg: "{{ file_content.stdout }}"

  # retrieve variable
  - name: Récupérer la variable FQDN du nœud cible
    ansible.builtin.command: "echo $FQDN"
    register: fqdn_result

  # check that variable existe
  - name: Vérifier que la variable FQDN est définie
    ansible.builtin.fail:
      msg: "La variable d'environnement FQDN n'est pas définie sur le nœud cible."
    when: fqdn_result.stdout == ""

  # add a line to the config file with retrieved variable
  - name: Ajouter la ligne Server=$FQDN dans le fichier de configuration
    ansible.builtin.lineinfile:
      path: "{{configFile}}"
      line: "MyServer={{ fqdn_result.stdout }}"
      state: present