---
- name: Désinstallation complete d'apache
  hosts: localhost
  become: yes

  tasks:
    - name: Vérifier si Apache 2 est installé
      ansible.builtin.apt:
        name: apache2
        state: absent
      register: apache_removed

    - name: Vérifier si le répertoire de configuration d'Apache2 existe
      ansible.builtin.stat:
        path: /etc/apache2
      register: apache2_config

    - name: Supprimer le répertoire de configuration d'Apache2 s'il existe
      ansible.builtin.file:
        path: /etc/apache2
        state: absent
      when: apache2_config.stat.exists

    - name: Supprimer d'autres fichiers de configuration ou dossiers liés à Apache2
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html   # Répertoire par défaut pour les fichiers web
        - /var/log/apache2 # Logs d'Apache
      when: apache_removed is changed or apache2_config.stat.exists
