services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-db
    env_file:
      - .env
    # network_mode: host
    ports:
      - "3306:${MYSQL_PORT}"
    volumes:    
      - ${MYSQL_DATA_VOLUME_DIR}:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf  # Monte le fichier de configuration
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}                       
        reservations:
          memory: ${MEM_RESERVATION}                
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    command: --default-authentication-plugin=mysql_native_password
